// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvvkohjekfusxftkobdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2dmtvaGpla2Z1c3hmdGtvYmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NzI1OTcsImV4cCI6MjA3MzE0ODU5N30.4gdlTVZ3Pbnubc4Z3KL_fbeYDy34ArLHEn8h61bR6oc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});